### ISSUE TITLE
Error when adding ParseLiveQuery to build gradle

### ISSUE THREAD

**Issue by Mykol00** [parse-community/ParseLiveQuery-Android#102]
I put this line in my root build.gradle:
maven { url "https://jitpack.io" }

and this line in my project build.gradle:
implementation 'com.github.parse-community:ParseLiveQuery-Android:1.1.0'

the gradle sync runs fine but when I attempt to build I get:
Error: Program type already present: com.parse.AbstractQueryController$1

Any ideas? I'm using back4app to host my parse server instance, could that be the problem?

**Comment by Jawnnypoo** [comment]
What does your Parse SDK dependency look like?

**Comment by Mykol00** [comment]
I think you mean this: 
implementation "com.parse:parse-android:1.17.1"
correct?

**Comment by Jawnnypoo** [comment]
That is the issue, it should be updated to `implementation "com.github.parse-community.Parse-SDK-Android:parse:1.19.0"`
