### ISSUE TITLE
Dependency on OkHttp 3.14 forces a minSdkVersion bump

### ISSUE THREAD

**Issue by jhansche** [parse-community/ParseLiveQuery-Android#113]
Parse-SDK-Android specifically locks the version to < 3.13, because OkHttp 3.13 increases their minSdkVersion to 21 (Android 5.0).  https://github.com/parse-community/Parse-SDK-Android/blob/master/parse/build.gradle#L31-L32

But #105 updated the OkHttp version to 3.14.  I think the OkHttp version should be aligned between the two (might be resolved if/when #112 is completed), and if LiveQuery doesn't have a specific need for OkHttp 3.13, it should be similar locked to 3.12 for the same reason.

**Comment by Jawnnypoo** [comment]
Good catch. This was a mistake when it was updated and we reverted it back in `Parse-SDK-Android`. Feel free to make a PR rolling this one back, or I can make one later today.

**Comment by jhansche** [comment]
For reference, the Parse-SDK-Android issue pointing out the same: https://github.com/parse-community/Parse-SDK-Android/issues/1005
And the commit that rolled it back: https://github.com/parse-community/Parse-SDK-Android/commit/11feb41fa728aa8432d840c9cc04b239c3909817

I'll push a PR for this shortly

**Comment by jhansche** [comment]
PR: #114
