### ISSUE TITLE
Parse Server LiveQuery Subscribe for Multiple contacts and Events

### ISSUE THREAD

**Issue by mr3h4n** [parse-community/ParseLiveQuery-Android#49]
I am developing Chatting Application for Android. I want to Subscribe Live Query for multiple Contacts in _User Class on Online Status of Users.

    `ParseQuery<ParseObject> query= ParseQuery.getQuery("_User");

        SubscriptionHandling<ParseObject> subscriptionHandling = parseLiveQueryClient.subscribe(query);

        subscriptionHandling.handleEvent(SubscriptionHandling.Event.CREATE,
                new SubscriptionHandling.HandleEventCallback<ParseObject>() {
                    @Override
                    public void onEvent(ParseQuery<ParseObject> query, ParseObject object) {

                    }
                });`
This Code works for all Users. But i want to trigger LiveQuery on selected Users. i want to do something like that... At Run time, WhenEver Application Launches.

`query.whereEqualsTo("username","USER1");
query.whereEqualsTo("username","USER2");`

**Comment by mmimeault** [comment]
Hello,

Can you explain what doesn't work with `query.whereEqualsTo("username","USER1");`
Live query should support that kind of query.

Thanks

**Comment by hermanliang** [comment]
I think it's not LiveQuery issue.
Your query using the `AND operator` will have no matching results.
You should use compound query to find selected users.
http://docs.parseplatform.org/android/guide/#compound-queries

ex.
```java
ParseQuery<ParseUser> query = ParseQuery.or(Arrays.asList(
    ParseUser.getQuery().whereEqualTo("username","USER1"),
    ParseUser.getQuery().whereEqualTo("username","USER2")
));
```

**Comment by naveedahmad99** [comment]
This helped me

**Comment by naveedahmad99** [comment]
ParseQuery<ParseUser> query = ParseQuery.or(Arrays.asList(
    ParseUser.getQuery().whereEqualTo("username","USER1"),
    ParseUser.getQuery().whereEqualTo("username","USER2")
));
