### ISSUE TITLE
Error in adding library through gradle

### ISSUE THREAD

**Issue by monajafi** [parse-community/ParseLiveQuery-Android#59]
After I added the lib using gradle and syncing I've got following error:
Error:Module 'com.parse:parse-livequery-android:1.0.3' depends on one or more Android Libraries but is a jar
How should I fix this?

**Comment by rogerhu** [comment]
For now add "aar" .. we will get this fixed up so the default is AAR as well

**Comment by rogerhu** [comment]
I.e. 1.0.3@aar

**Comment by monajafi** [comment]
Thanks, It's fixed . now
