### ISSUE TITLE
Error with Parse android sdk version 1.15.6

### ISSUE THREAD

**Issue by monajafi** [parse-community/ParseLiveQuery-Android#60]
I faced the following error with latest parse android sdk (1.15.6):
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/parse/BuildConfig;

This error goes away with the 1.15.1 sdk version
I enaled multidex and after run following error occured:
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/parse/BuildConfig.class

I can't figure out the solution

**Comment by hermanliang** [comment]
It probably due to the dependencies of the `ParseLiveQuery-Android` not update to the latest Parse SDK.
You may try to setup using the following syntax
```groovy
dependencies {
    compile 'com.parse:parse-android:1.15.6'
    compile('com.parse:parse-livequery-android:1.0.3', {
        exclude group: 'com.parse', module: 'parse-android'
    })
}
```

**Comment by monajafi** [comment]
Great, It's working perfectly now thanks

**Comment by hermanliang** [comment]
@monajafi This issue has been resolved in the latest LiveQuery.
Now you may declare the dependencies like this
```groovy
dependencies {
    compile 'com.parse:parse-android:1.15.6'
    compile 'com.parse:parse-livequery-android:1.0.4@aar'
}
```

**Comment by monajafi** [comment]
Thanks a lot here is the latest library which is working fine:
```
dependencies {
    compile 'com.parse:parse-android:1.15.7'
    compile 'com.parse:parse-livequery-android:1.0.4'
}
```

**Comment by mmimeault** [comment]
@hermanliang can we close this issue if this is fixed?

**Comment by hermanliang** [comment]
@mmimeault yeah, the issue has been fixed. We can close this issue.
