### ISSUE TITLE
Complex queries don't work

### ISSUE THREAD

**Issue by WanClem** [parse-community/ParseLiveQuery-Android#65]
Hi guys, nice job on LiveQueries support. Just started to try it out today and discovered that complex queries don't work, but simple queries do

Example 

>ParseQuery<ParseUser> usersQuery = ParseUser.getQuery();
usersQuery.whereEqualTo("category", "android-pals"); 
 SubscriptionHandling<ParseUser>subscriptionHandling=ApplicationLoader.getParseLiveQueryClient().subscribe(usersQuery);

LiveQueries work with the  above query all the time.

But when I tried to do 
>ParseQuery<ParseUser> usersQuery = ParseUser.getQuery();
 usersQuery.whereEqualTo("category", "android-pals");
 usersQuery.whereEqualTo("privilegde", "premium");
 SubscriptionHandling<ParseUser> subscriptionHandling = ApplicationLoader.getParseLiveQueryClient().subscribe(usersQuery);

Then LiveQueries don't work again

Am I missing something?

**Comment by flovilmart** [comment]
Those are probably not supported on parse-server itself. https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification#subscribe-message

**Comment by mmimeault** [comment]
Hello,

Thank you for trying the live query cllient.

"privilegde" is the right field you are trying to query?

Thanks

**Comment by WanClem** [comment]
Yes, privilege is the right field. Nonetheless, I tried a couple times and it didn't work so I have managed to switch to single queries and I think am fine now...Nice job guys..👍
