### ISSUE TITLE
Does subscriptionHandling.handleEvents callback will keep on refreshing as new Data will be updated?

### ISSUE THREAD

**Issue by sandeep2242** [parse-community/ParseLiveQuery-Android#71]
I have one query regarding live query, Does subscriptionHandling.handleEvents callback will keep on refreshing as new Data will be updated on regural intervals?

**Comment by flovilmart** [comment]
The event will fire every times a new object matching your query is available or an existing object is updated.

**Comment by sandeep2242** [comment]
ok Thanks a  ton.
