### ISSUE TITLE
Parse liveQuery return null

### ISSUE THREAD

**Issue by memishood** [parse-community/ParseLiveQuery-Android#96]
`
val liveQueryClient = ParseLiveQueryClient.Factory.getClient()
val pQuery = ParseUser.getQuery() // or ParseQuery.getQuery<ParseUser>("_User")
pQuery.whereEqualTo("objectId",ParseUser.getCurrentUser().objectId)

val sub = liveQueryClient.subscribe(pQuery)
        sub.handleEvents { _, _, objects ->
            walletButton.text = "${objects.getString("count")}"
            Log.d("FeedActivity","event: " + objects.getString("count")) // it returns event: null in logcat
        }
`
when i update count in parse user class, returns its value null

**Comment by mmimeault** [comment]
Hello,

You already closed the issue, can you provide some detail on if you found the solution?

Thanks
